<?php

/*
 * phpMyEdit language file
 *
 * language: unknown (portuguese? than this file shoud be PME.lang.PT.inc)
 * encoding: iso-8859-1
 * date: 02/2002
 * author: unknown
 */

return Array(
		'Prev'          =>'Precedente',
		'Add'           =>'Adicione',
		'Copy'         	=>'Cópia',
		'Change'        =>'Mude',
		'Delete'        =>'Suprima',
		'View'      	=>'Indicador',
		'Next'          =>'Seguinte',
		'Page'          =>'Página',
		'Records'       =>'Registros',
		'Save'          =>'Excepto',
		'More'          =>'Mais',
		'Cancel'        =>'cancelamento',
		'of'			=>'/', // untranslated
		'record added'  =>'suprimido mudado',
		'record changed'=>'Record adicionado',
		'record deleted'=>'Record record',
		'Please enter'  =>'Por favor entram ',
		'months' =>	Array(
			'01'=>'Janeiro',
			'02'=>'Fevereiro',
			'03'=>'Março',
			'04'=>'Abril',
			'05'=>'Pode',
			'06'=>'Junho',
			'07'=>'Julho',
			'08'=>'Agosto',
			'09'=>'Setembro',
			'10'=>'Outubro',
			'11'=>'Novembro',
			'12'=>'Dezembro')
		);

?>
