<?php

/*
 * phpMyEdit language file
 *
 * language: italian (standard)
 * encoding: iso-8859-1
 * date: 02/2002
 * author: unknown
 */

return Array(
		'Prev'          =>'Precedente',
		'Add'           =>'Aggiungire',
		'Copy'         	=>'Copia',
		'Change'        =>'Modifica',
		'Delete'        =>'Cancella',
		'View'      	=>'Visualizza',
		'Next'          =>'Seguente',
		'Page'          =>'Pagina',
		'Records'       =>'Record',
		'Save'          =>'Salva',
		'More'          =>'Salva & Continua',
		'Cancel'        =>'Annulla',
		'of'			=>'/', // untranslated
		'record added'  =>'Il record è stato aggiunto',
		'record changed'=>'Il record è stato cambiato',
		'record deleted'=>'Il record è stato cancellato',
		'Please enter'  =>'Prego inserire',
		'months'	=> Array(
			'01'=>'Gennaio',
			'02'=>'Febbraio',
			'03'=>'Marzo',
			'04'=>'Aprile',
			'05'=>'Può',
			'06'=>'Giugno',
			'07'=>'Luglio',
			'08'=>'Agosto',
			'09'=>'Settembre',
			'10'=>'Ottobre',
			'11'=>'Novembre',
			'12'=>'Dicembre')
		);

?>
