<?php

/*
 * phpMyEdit language file
 *
 * language: german (standard)
 * encoding: iso-8859-1
 * date: 07/2002
 * author: Christof Brandstetter <fellz@users.sourceforge.net>
 * info: http://sourceforge.net/tracker/index.php?func=detail&aid=524371&group_id=12479&atid=212479
 */

return Array(
		'Prev'          =>'Zurueck',
		'Add'           =>'Hinzufuegen',
		'Copy'         	=>'Kopieren',
		'Change'        =>'Aendern',
		'Delete'        =>'Loeschen',
		'View'      	=>'Anzeigen',
		'Next'          =>'Weiter',
		'Page'          =>'Seite',
		'Records'       =>'Datensaetze',
		'Save'          =>'Speichern',
		'More'          =>'Speichern, weiteren Datensatz hinzufuegen',
		'Cancel'        =>'Abbrechen',
		'of'			=>'von', // translated correctly?
		'record added'  =>'Datensatz hinzugefuegt',
		'record changed'=>'Datensatz geaendert',
		'record deleted'=>'Datensatz geloescht',
		'Please enter'  =>'Bitte fuellen sie dieses Feld aus:',
		'months' =>	Array(
			'01'=>'Januar',
			'02'=>'Februar',
			'03'=>'März',
			'04'=>'April',
			'05'=>'Mag',
			'06'=>'Juni',
			'07'=>'Juli',
			'08'=>'August',
			'09'=>'September',
			'10'=>'Oktober',
			'11'=>'November',
			'12'=>'Dezember')
		);

/* OLD. Wrong?

   return Array(
   'Prev'          =>'Vorhergehendes',
   'Add'           =>'Fügen',
   'Copy'         	=>'Copieren',
   'Change'        =>'Sätze Der Seite Zunächst',
   'Delete'        =>'Fügen Sie Satz hinzu.',
   'View'      	=>'Bildschirmanzeige',
   'Next'          =>'Der Löschung',
   'Page'          =>'Der Änderung',
   'Records'       =>'Hinzu, die',
   'Save'          =>'Außer',
   'More'          =>'Fügen Sie mehr hinzu',
   'Cancel'        =>'Löschen',
   'record added'  =>'Speichern Hinzufügten',
   'record changed'=>'Speichern Änderten',
   'record deleted'=>'Speichern Löschten',
   'Please enter'  =>'Bitte Eingeben',
   );

 */

?>
