<?php

/*
 * phpMyEdit language file
 *
 * language: french (standard) 
 * encoding: iso-8859-1
 * date: 02/2002
 * author: unknown
 */

return Array(
		'Prev'          =>'Précédent',
		'Add'           =>'Ajoutez',
		'Copy'         	=>'Copient',
		'Change'        =>'Changez',
		'Delete'        =>'Effacez',
		'View'      	=>'Affichage',
		'Next'          =>'Prochain',
		'Page'          =>'La page',
		'Records'       =>'Enregistrements',
		'Save'          =>'Économiser',
		'More'          =>'Plus',
		'Cancel'        =>'Annulation',
		'of'			=>'/', // untranslated
		'record added'  =>'L\'enregistrement a été ajouté',
		'record changed'=>'L\'enregistrement a été changé',
		'record deleted'=>'L\'enregistrement a été effacé',
		'Please enter'  =>'Entrez S\'il vous plaît',
		'months'	=> Array(
			'01'=>'Janvier',
			'02'=>'Février',
			'03'=>'Mars',
			'04'=>'Avril',
			'05'=>'Peut',
			'06'=>'Juin',
			'07'=>'Juillet',
			'08'=>'Août',
			'09'=>'Septembre',
			'10'=>'Octobre',
			'11'=>'Novembre',
			'12'=>'Décembre')
		);

?>
