<?php

/*
 * phpMyEdit language file
 *
 * language: spanish
 * encoding: iso-8859-1
 * date: 02/2002
 * author: unknown
 */

return Array(
		'Prev'          =>'Anterior',
		'Add'           =>'Agregue',
		'Copy'         	=>'Copian',
		'Change'        =>'Cambie',
		'Delete'        =>'Suprima',
		'View'      	=>'Visualización',
		'Next'          =>'Siguiente',
		'Page'          =>'Paginación',
		'Records'       =>'Expedientes',
		'Save'          =>'Excepto',
		'More'          =>'Más',
		'Cancel'        =>'Cancelación',
		'of'			=>'/', // untranslated
		'record added'  =>'Haber suprimido cambiante',
		'record changed'=>'De registro agregado',
		'record deleted'=>'De registro de registro',
		'Please enter'  =>'Por favor introducen ',
		'months'	=> Array(
			'01'=>'Enero',
			'02'=>'Febrero',
			'03'=>'Marcha',
			'04'=>'Abril',
			'05'=>'Puede',
			'06'=>'Junio',
			'07'=>'Julio',
			'08'=>'Agosto',
			'09'=>'Septiembre',
			'10'=>'Octubre',
			'11'=>'Noviembre',
			'12'=>'Diciembre')
		);

?>
